### ISSUE TITLE
Botconf Slides URL 

### ISSUE THREAD

**Issue by alexander-hanel** [danielplohmann/docker-mcrit#1]
Hey @danielplohmann, 

The URL for the botconf slides in the [History](https://github.com/danielplohmann/docker-mcrit#history) section has changed from

```
 https://www.botconf.eu/wp-content/uploads/2023/04/2023-15-Plohmann_MCRIT.pdf
```
to 

```
https://www.botconf.eu/wp-content/uploads/formidable/2/2023-15-Plohmann_MCRIT.pdf
```

**Comment by danielplohmann** [comment]
Hey Alex, 

thanks a lot for the pointer! I have fixed the link.

Best Regards

Daniel
