### ISSUE TITLE
Question about uploading Malpedia dataset to Mcrit

### ISSUE THREAD

**Issue by Tricker-z** [danielplohmann/docker-mcrit#2]
Hi developers of Mcrit

I am trying to deploy Mcrit locally with docker for malicious sample detection. Unfortunately, I found no sample data in the database after startup. So please let me know if there is a quick way to upload Malpedia malicious sample dataset to McritWeb and then perform malicious sample detection :)

Hope to hear from you soon

Best Regards

**Comment by danielplohmann** [comment]
Hi!

That's correct, we are currently thinking about how it would be possible to ship the full Malpedia data in a pre-processed fashion.
Please note: as the Malpedia data set itself is still considered being shared under TLP:AMBER, we are thinking of an in-between solution that would still allow us sharing the data, quite possibly by dropping the contained assembly (this primarily also for size reasons, full SMDA disassembly of unpacked contents in Malpedia currently sit at 30GB+) and masking the file hashes.

For library code, I have recently set up this repository:

https://github.com/danielplohmann/mcrit-data

For now it contains reference code for almost all MinGW and aPLib releases, and some for MSVC and libzlib.
More to come, as I re-process my scattered data sitting in several places. :)

That's however useful if you already want to experiment and play with MCRIT itself.

**Comment by Tricker-z** [comment]
Hi

Thanks for your reply! Acutually, I've downloaded all the malicious samples  from Malpedia, can I upload it directly to Mcrit with the cli-tools? Since I find that the submit handler has a built-in disaseembler in `getSmdaReportFromFilepath()`.

In short, I have samples and family tags on hand, can I build Mcrit's database with the command line tool?

Thanks very much!

**Comment by danielplohmann** [comment]
Oh okay, 
if you really want to go that route and do the processing yourself, there is a much easier way.

In the MCRIT repository, there is a script that does complete parallelized batch processing of the entire Malpedia repo and it will ensure adding correct family/version tags plus use ApiScout to also have dynamic API usage reconstruction for all the memory dumps:

https://github.com/danielplohmann/mcrit/blob/main/examples/smda_collection.py

I'd recommend using this for what you want to do. :)

**Comment by Tricker-z** [comment]
Hi

I'm trying to use `smda_collection.py` to automatically process the samples from Malpedia. Unfortunately, I encountered a runtime error. In specific, all the binary files do not pass the check of `isNativeCode` in function `work()` line 203 :(

```python
def work(input_element):
  ...
    identifier = NativeCodeIdentifier()
    if not identifier.isNativeCode(INPUT_FILEPATH):
         return
```

It seems indentify the files as .Net, so I'm wondering if I made a mistake (all the downloaded files match the sha256).  
Temporarily, I commented out this check to generate the corresponding .smda files.

```python
    def isNativeCode(self, filepath):
        for family in self.family_override:
            if family in filepath:
                return True
        content = ""
        with open(filepath, "rb") as fin:
            content = fin.read()
        ### We want to process both Delphi and Go for this, so ensure they are not excluded.
        # identify Delphi
        # is_delphi = self._identifyDelphi(content)
        is_delphi = False
        # identify Go
        # is_go = self._identifyGo(content)
        is_go = False
        # identify .NET
        is_dotnet = self._identifyDotnet(content)
        # identify PyInstaller
        is_python = self._identifyPython(content)
        return not (is_delphi or is_go or is_dotnet or is_python)
```

Hope to hear from you soon

**Comment by danielplohmann** [comment]
Hey!
So generally, it's not an issue if you just comment that out. 
It will just mean that the specific language types will be treated as normal native code. 
Actually, by now SMDA can understand Delphi and Go specifically, so those are fully parsed with symbols.
.NET files will possibly have a few misidentified functions, which should not hurt too much, same for Python.

Otherwise, could you post the full exception/traceback, from your description I cannot infer what's going wrong because the script is working for me. :-/

**Comment by danielplohmann** [comment]
I guess this is resolved then.
