### ISSUE TITLE
easier version-dependent build

### ISSUE THREAD

**Issue by malwarefrank** [danielplohmann/docker-mcrit#5]
I have to keep track of which version I am building and using in an offline system, and it is somewhat cumbersome to remember which files to change.  So I am using a `.env` file and variables in the docker-compose.yml and Dockerfile's.  Are you open to that change?  I can submit a PR with what I have put together if so

**Comment by danielplohmann** [comment]
Hey!
Yes, please do a pull request for what you described, I'm happy to integrate it!
As I'm in the now seemingly luxurious position to simply always pull the repo on my production/test instance when upgrading and thus not being aware of how upgrades look in offline deployments that sounds like a useful improvement.
